version: '2.1'
orbs:
  gcp-gcr: circleci/gcp-gcr@0.15.1

filters: &filters
  tags:
    only: /.*/

workflows:
  build_and_push_image:
    jobs:
      - gcp-gcr/build-and-push-image:
          context: gcp
          image: app/webapp
          registry-url: europe-west1-docker.pkg.dev
          tag: $CIRCLE_TAG
          filters:
            tags:
              only: /.*/
          # setup-remote-docker: true
          # use-docker-layer-caching: true